version: 2
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: task-test
          MYSQL_USER: spring
          MYSQL_PASSWORD: Spring12345
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./mvnw test
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import todolist-test data; run an example query
          command: |
            sudo apt install -y mysql-client
            mysql -h 127.0.0.1 -P 3306 -u root --password=1234 --execute="use task-test;"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
