
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
      environment:
        DB_ROOT_USER: root
        DB_URL: jdbc:mysql://localhost:3306/task_test
        DB_DRIVER: com.mysql.cj.jdbc.Driver
        DB_PASS: ""
        MAVEN_OPTS: -Xmx3200m
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Wait for Database Connection
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run: sudo apt install -y mysql-client
    - run: mysql -h 127.0.0.1 -u root --execute="create database test_db"
    # Download and cache dependencies
    - restore_cache:
        keys:
        -  v1-dependencies-{{ checksum "pom.xml" }}
        -  v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
        # run tests!
    - run: mvn test
