
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:11.0.3-jdk-stretch
      #specify system properties
      environment:
        DB_ROOT_USER: root
        DB_URL: jdbc:mysql://localhost:3306/testdb
        DB_DRIVER: com.mysql.cj.jdbc.Driver
        DB_PASS: ""
  # Customize the JVM maximum heap limit
        MAVEN_OPTS: -Xmx3200m
      # Specify our database service here
      # CircleCI maintains a library of pre-built images
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Wait for Database Connection
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
  #install mysql client
    - run: sudo apt-get install mysql-client
  # create databases
    - run: mysql -h 127.0.0.1 -u root -e "create database task_test"
    # Download and cache dependencies
    - restore_cache:
        keys:
        -  v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        -  v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
        # run tests!
    - run: mvn integration-test
